#!/usr/bin/env bash
# setup-demo.sh — 一鍵建立 RaceOne Demo 環境
# 用法: ./scripts/setup-demo.sh <SUPABASE_DEMO_URL> <SUPABASE_DEMO_ANON_KEY> [SUPABASE_SERVICE_ROLE_KEY]
# 範例: ./scripts/setup-demo.sh https://xyz.supabase.co eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... sbp_xxx

set -euo pipefail

# 顏色輸出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# 參數檢查
if [ $# -lt 2 ]; then
  log_error "用法: $0 <SUPABASE_DEMO_URL> <SUPABASE_DEMO_ANON_KEY> [SUPABASE_SERVICE_ROLE_KEY]"
  exit 1
fi

DEMO_URL="$1"
DEMO_ANON_KEY="$2"
DEMO_SERVICE_KEY="${3:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

log_info "RaceOne Demo 環境建立開始"
log_info "目標 Supabase: $DEMO_URL"

# 1. 建立 demo 專用環境變數檔
log_info "建立 .env.demo ..."
cat > "$PROJECT_ROOT/.env.demo" <<EOF
# RaceOne Demo Mode Configuration
# Generated by setup-demo.sh at $(date -u +"%Y-%m-%d %H:%M:%S UTC")

NEXT_PUBLIC_SUPABASE_URL=$DEMO_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$DEMO_ANON_KEY
NEXT_PUBLIC_APP_URL=https://demo.raceone.ai
NEXT_PUBLIC_DEMO_MODE=true

# 關閉外部整合（Demo 模式不發送真實通知/同步）
DISABLE_NOTION_SYNC=true
DISABLE_EMAIL_SEND=true
DISABLE_BOT_WEBHOOK=true
MOCK_PAYMENT_WEBHOOK=true
MOCK_TIMING_REALTIME=true

# Demo 模式專用：固定種子資料版本
DEMO_SEED_VERSION=2026.08.14
EOF

if [ -n "$DEMO_SERVICE_KEY" ]; then
  echo "SUPABASE_SERVICE_ROLE_KEY=$DEMO_SERVICE_KEY" >> "$PROJECT_ROOT/.env.demo"
  log_info "已加入 Service Role Key（用於建立 demo 帳號）"
fi

log_success ".env.demo 建立完成"

# 2. 檢查 psql 可用性
if ! command -v psql &> /dev/null; then
  log_error "psql 未安裝，請先安裝 PostgreSQL client tools"
  exit 1
fi

# 3. 執行 Migration（去掉管理員專用 RLS Policy）
log_info "執行資料庫 Migration（過濾管理員專用 Policy）..."

MIGRATION_DIR="$PROJECT_ROOT/supabase/migrations"
if [ ! -d "$MIGRATION_DIR" ]; then
  log_warn "找不到 $MIGRATION_DIR，跳過 migration"
else
  # 建立暫存合併 SQL，過濾掉 super_admin/finance 專用的較寬鬆 Policy
  TEMP_SQL=$(mktemp)
  trap "rm -f $TEMP_SQL" EXIT
  
  cat > "$TEMP_SQL" <<'SQL'
-- RaceOne Demo Migration Runner
-- 此腳本會跳過：super_admin/finance 專用的寬鬆存取 Policy
-- 保留：租戶隔離基礎 Policy、一般角色 Policy

\set ON_ERROR_STOP on
SQL

  for f in "$MIGRATION_DIR"/*.sql; do
    if [ -f "$f" ]; then
      log_info "  處理: $(basename "$f")"
      # 過濾邏輯：跳過包含 "super_admin" 或 "finance" 且為 PERMISSIVE 寬鬆 Policy 的語句
      # 保留租戶隔離 (_tenant_isolation) 和一般角色 Policy
      grep -v -E "CREATE POLICY.*(super_admin|finance).*FOR (ALL|SELECT|INSERT|UPDATE|DELETE).*USING.*true" "$f" \
        | grep -v -E "CREATE POLICY.*(super_admin|finance).*WITH CHECK.*true" \
        >> "$TEMP_SQL"
      echo "" >> "$TEMP_SQL"
    fi
  done
  
  # 執行合併後的 SQL
  if psql "$DEMO_URL" -f "$TEMP_SQL" -v ON_ERROR_STOP=1 -q; then
    log_success "Migration 執行完成"
  else
    log_error "Migration 執行失敗，請檢查錯誤訊息"
    exit 1
  fi
fi

# 4. 執行 Demo Seed Data
log_info "填入 Demo 種子資料..."

SEED_SQL="$SCRIPT_DIR/demo-seed.sql"
if [ ! -f "$SEED_SQL" ]; then
  log_warn "找不到 $SEED_SQL，將自動建立基本 seed"
  SEED_SQL=$(mktemp)
  cat > "$SEED_SQL" <<'SQL'
-- RaceOne Demo Seed Data (Auto-generated)
-- 僅建立 1 個 tenant、1 個賽事、少量公開資料

\set ON_ERROR_STOP on

-- 1. 建立 Demo Tenant
INSERT INTO tenants (id, name, slug, created_at)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'RaceOne Demo',
  'raceone-demo',
  now()
) ON CONFLICT (id) DO NOTHING;

-- 2. 建立 Demo 賽事
INSERT INTO race_events (id, tenant_id, name, slug, description, start_date, end_date, location, status, created_at)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  '00000000-0000-0000-0000-000000000001',
  '2026 長明超馬 Demo',
  'changming-ultra-2026-demo',
  '這是 RaceOne 平台的 Demo 賽事，展示完整報名、計時、簽到流程',
  '2026-10-15 06:00:00+08',
  '2026-10-15 18:00:00+08',
  '台中市長明國中',
  'published',
  now()
) ON CONFLICT (id) DO NOTHING;

-- 3. 建立賽事組別
INSERT INTO race_categories (id, event_id, name, distance_km, quota, price_cents, status, created_at)
VALUES 
  ('22222222-2222-2222-2222-222222222221', '11111111-1111-1111-1111-111111111111', '100K 組', 100, 100, 350000, 'open', now()),
  ('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111', '50K 組', 50, 200, 200000, 'open', now()),
  ('22222222-2222-2222-2222-222222222223', '11111111-1111-1111-1111-111111111111', '25K 組', 25, 300, 120000, 'open', now())
ON CONFLICT (id) DO NOTHING;

-- 4. 建立公開公告
INSERT INTO news_posts (id, event_id, tenant_id, title, content_md, status, published_at, created_at)
VALUES 
  ('33333333-3333-3333-3333-333333333331', '11111111-1111-1111-1111-111111111111', '00000000-0000-0000-0000-000000000001',
   '歡迎來到 RaceOne Demo！',
   '<p>這是 <strong>RaceOne 超馬賽事管理平台</strong> 的公開 Demo 環境。</p><p>您可以使用 <code>viewer@demo.raceone.ai</code> / <code>demo1234</code> 登入體驗跑者視角，或使用 <code>admin@demo.raceone.ai</code> / <code>demo1234</code> 體驗後台管理功能（僅限查看）。</p>',
   'published', now(), now())
ON CONFLICT (id) DO NOTHING;

SQL
fi

if psql "$DEMO_URL" -f "$SEED_SQL" -v ON_ERROR_STOP=1 -q; then
  log_success "Demo 種子資料填入完成"
else
  log_error "種子資料填入失敗"
  exit 1
fi

# 5. 建立 Demo 帳號（需要 Service Role Key）
if [ -n "$DEMO_SERVICE_KEY" ]; then
  log_info "建立 Demo 帳號（透過 Supabase Auth Admin API）..."
  
  # 使用 curl 呼叫 Supabase Management API
  ADMIN_API="https://api.supabase.com/v1/projects/$(echo $DEMO_URL | sed -E 's|https://([^.]+)\.supabase\.co|\1|')"
  
  # 注意：實際建立用戶需用 Supabase Dashboard 或 CLI
  # 這裡提供手動建立指引
  log_warn "請手動在 Supabase Dashboard > Authentication > Users 建立以下帳號："
  echo ""
  echo "  1. admin@demo.raceone.ai / demo1234"
  echo "     → User Metadata: {\"role\":\"super_admin\",\"tenant_id\":\"00000000-0000-0000-0000-000000000001\"}"
  echo "     → Email Confirm: true"
  echo ""
  echo "  2. finance@demo.raceone.ai / demo1234"
  echo "     → User Metadata: {\"role\":\"finance\",\"tenant_id\":\"00000000-0000-0000-0000-000000000001\"}"
  echo "     → Email Confirm: true"
  echo ""
  echo "  3. viewer@demo.raceone.ai / demo1234"
  echo "     → User Metadata: {\"role\":\"viewer\",\"tenant_id\":\"00000000-0000-0000-0000-000000000001\"}"
  echo "     → Email Confirm: true"
  echo ""
  
  # 嘗試透過 SQL 直接寫入 auth.users（需 service role）
  cat > /tmp/create-demo-users.sql <<'SQL'
-- 嘗試直接插入 auth.users（僅限 service role 執行）
-- 注意：Supabase 不建議直接操作 auth schema，請優先用 Dashboard

INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at, role, aud)
VALUES 
  (gen_random_uuid(), 'admin@demo.raceone.ai', crypt('demo1234', gen_salt('bf')), now(), '{"role":"super_admin","tenant_id":"00000000-0000-0000-0000-000000000001"}'::jsonb, now(), now(), 'authenticated', 'authenticated'),
  (gen_random_uuid(), 'finance@demo.raceone.ai', crypt('demo1234', gen_salt('bf')), now(), '{"role":"finance","tenant_id":"00000000-0000-0000-0000-000000000001"}'::jsonb, now(), now(), 'authenticated', 'authenticated'),
  (gen_random_uuid(), 'viewer@demo.raceone.ai', crypt('demo1234', gen_salt('bf')), now(), '{"role":"viewer","tenant_id":"00000000-0000-0000-0000-000000000001"}'::jsonb, now(), now(), 'authenticated', 'authenticated')
ON CONFLICT (email) DO NOTHING;

-- 同步建立 profiles
INSERT INTO profiles (id, tenant_id, role, full_name, created_at)
SELECT id, '00000000-0000-0000-0000-000000000001', (raw_user_meta_data->>'role')::user_role, 
       CASE (raw_user_meta_data->>'role') 
         WHEN 'super_admin' THEN 'Demo 管理員'
         WHEN 'finance' THEN 'Demo 財務'
         ELSE 'Demo 觀看者'
       END,
       now()
FROM auth.users
WHERE email IN ('admin@demo.raceone.ai', 'finance@demo.raceone.ai', 'viewer@demo.raceone.ai')
ON CONFLICT (id) DO NOTHING;
SQL

  log_info "嘗試自動建立用戶（需要 service role 權限）..."
  if psql "$DEMO_URL" -f /tmp/create-demo-users.sql -v ON_ERROR_STOP=1 -q 2>/dev/null; then
    log_success "Demo 帳號自動建立成功"
  else
    log_warn "自動建立失敗（權限不足），請依上述指引手動建立"
  fi
  rm -f /tmp/create-demo-users.sql
else
  log_warn "未提供 Service Role Key，跳過自動建立帳號"
  log_info "請手動在 Supabase Dashboard 建立上述 3 個帳號"
fi

# 6. 完成總結
echo ""
log_success "========================================"
log_success "RaceOne Demo 環境建立完成！"
log_success "========================================"
echo ""
echo "下一步："
echo "  1. 將 .env.demo 複製為 .env.local（或部署到 Vercel 環境變數）"
echo "  2. 執行: pnpm build && pnpm start  (本地測試)"
echo "  3. 或推送到 Vercel 部署到 demo.raceone.ai"
echo ""
echo "Demo 帳號："
echo "  管理員: admin@demo.raceone.ai / demo1234"
echo "  財務:   finance@demo.raceone.ai / demo1234"
echo "  觀看者: viewer@demo.raceone.ai / demo1234"
echo ""
echo "相關檔案："
echo "  - 環境變數: $PROJECT_ROOT/.env.demo"
echo "  - Seed SQL: $SEED_SQL"
echo "  - Demo 守衛: $PROJECT_ROOT/src/lib/demo-mode.ts"